# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contadorPalavras.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ontadorPalavras.proto\x12\x08palavras\"!\n\rListaPalavras\x12\x10\n\x08palavras\x18\x01 \x03(\t\")\n\x0bQtdPalavras\x12\x1a\n\x12quantidadePalavras\x18\x01 \x01(\x05\"8\n\x11PalavraVerificada\x12\x0f\n\x07palavra\x18\x01 \x01(\t\x12\x12\n\nquantidade\x18\x02 \x01(\x05\x32\xa9\x01\n\x10\x43ontadorPalavras\x12\x46\n\x12\x43\x61lcularQuantidade\x12\x17.palavras.ListaPalavras\x1a\x15.palavras.QtdPalavras\"\x00\x12M\n\x11VerificarPalavras\x12\x17.palavras.ListaPalavras\x1a\x1b.palavras.PalavraVerificada\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contadorPalavras_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTAPALAVRAS._serialized_start=36
  _LISTAPALAVRAS._serialized_end=69
  _QTDPALAVRAS._serialized_start=71
  _QTDPALAVRAS._serialized_end=112
  _PALAVRAVERIFICADA._serialized_start=114
  _PALAVRAVERIFICADA._serialized_end=170
  _CONTADORPALAVRAS._serialized_start=173
  _CONTADORPALAVRAS._serialized_end=342
# @@protoc_insertion_point(module_scope)
